services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/.docker/Dockerfile
    container_name: twitter_clone_backend
    # The command is now run from the Dockerfile's CMD
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    env_file:
      - ./packages/backend/.env
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/twitter_clone
    # NO VOLUMES FOR SOURCE CODE
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/.docker/Dockerfile
    container_name: twitter_clone_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      # These are still needed for Create React App
      - WDS_SOCKET_PORT=0
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    # NO VOLUMES FOR SOURCE CODE
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: