services:
  mariadb:
    image: mariadb:11
    container_name: mariadb_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: twitter_clone
      MYSQL_USER: twitter_user
      MYSQL_PASSWORD: twitter_password
    volumes:
      - mariadb_data:/var/lib/mysql
      # Optional: Add init scripts
      # - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/.docker/Dockerfile
    container_name: twitter_clone_backend
    ports:
      - "3001:3001"
    depends_on:
      - mariadb
    env_file:
      - ./packages/backend/.env
    environment:
      - NODE_ENV=development
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=twitter_user
      - DB_PASSWORD=twitter_password
      - DB_NAME=twitter_clone
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/.docker/Dockerfile
    container_name: twitter_clone_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data: